export * from './isArray'
export * from './isFunction'
export * from './isNumber'
export * from './isString'
export * from './isTime'
export * from './isUtil'
export * from './isObject'
export * from './isColor'

export * from './type'