import './iterator'
import './isArray'
import './isFunction'
import './isNumber'
import './isString'
import './isTime'
import './isUtil'
import './type'
import './is'

import './empty'
import './error'
import './isObject'
import './map'
import './promise'